print("**********WELCOME TO FUN FACTS**********")
print("1. There are more twins now than ever before." , end = "*****") 
print("2. The hottest chili pepper in the world is so hot it could kill you.")
print("3. the world's most densely populated island is the size of two soccer feilds")
print("4. the canary island are named after dogs, not birds. ")
print("5. Indonesia is home to some of the shortest people in the world.")
print("6. The entire world's population could fit inside Los Angeles.")
print("7. The world's quietest room is located at Microsoft's headquarters in Washington state")
print("8. The world's quietest room is located at Microsoft's headquarters in Washington state")
print("9. The Paris Agreement on climate change was signed by the largest number of countries ever in one day.")
print("10. The longest place name on the planet is 85 letters long.")
print("11. There are only three countries in the world that don't use the metric system.")
print("12. Four babies are born every second. ")
print("13. The coldest temperature sever recorded was -144 degrees Fahrenheit.")
print("14. The Earth's ozone layer will make a full recovery in 50 years.")
print("15. Japan is the world's most earthquake-prone country.")
print("16. There are around 4 quadrillion quadrillion bacteria on Earth. ")
print("17. Africa and Asia are home to nearly 90 percent of the world's rural population.")
print("18. The world's largest man-made oyster reef was created in Maryland.")
print("19. Only two countries use purple in their national flags.*****")
print("20. Muhammad is thought to be the most popular name in the world.*****")
