print("1.Fact: Blue whales eat half a million calories in one mouthful")
print("2.That tiny pocket in jeans was designed to store pocket watches")
print("3.Most Disney characters wear gloves to keep animation simple")
print("4.The current American flag was designed by a high school student")
print("5.Cows don’t have upper front teeth")
print("6.Only a quarter of the Sahara Desert is sandy")
print("7.Bananas grow upside-down")
print("8.There were active volcanoes on the moon when dinosaurs were alive")
print("9.Dogs sniff good smells with their left nostril")
print("10.Avocados were named after reproductive organs")
print("11.T. S. Eliot wore green makeup")
print("12.No number before 1,000 contains the letter A")
print("13.The # symbol isn’t officially called hashtag or pound")
print("14.You can thank the Greeks for calling Christmas “Xmas”")
print("15.Movie trailers originally played after the movie")
print("16.The U.S. government saved every public tweet from 2006 through 2017")
print("17.Theodore Roosevelt had a pet hyena")
print("18.Cap’n Crunch’s full name is Horatio Magellan Crunch")
print("19.The CIA headquarters has its own Starbucks, but baristas don’t write names on the cups")
print("20.Giraffe tongues can be 20 inches long")
